IDENTIFICATORDIVISION. PROGRAMID. PROGRAM5.
	
	PROCEDUREDIVISION.	
		
		INTEGER SOMA SECTION. INTEGER n1 INTEGER n2
	
			BEGINDECLARATIONS
			ENDDECLARATIONS
			
			RETURN (n1 + n2).
			
			ENDCOM.
				
		ENDPROC.
		
		INTEGER SUB SECTION. INTEGER n1 INTEGER n2
	
			BEGINDECLARATIONS
			ENDDECLARATIONS
			
			RETURN (n1 - n2).
			
			ENDCOM.
				
		ENDPROC.
		
		INTEGER MULT SECTION. INTEGER n1 INTEGER n2
	
			BEGINDECLARATIONS
			ENDDECLARATIONS
			
			RETURN (n1 * n2).
			
			ENDCOM.
				
		ENDPROC.
		
		#INTEGER DIV SECTION. INTEGER n1 INTEGER n2
	
		#	BEGINDECLARATIONS
		#	ENDDECLARATIONS
			
		#	RETURN (n1 / n2).
			
		#	ENDCOM.
				
		#ENDPROC.
			
		MAIN SECTION.
			
			BEGINDECLARATIONS
				a PIC INTEGER.
				b PIC INTEGER.
				r PIC INTEGER.
			ENDDECLARATIONS
			
			MOVE 3 TO a.
			MOVE 2 TO b.
					 
			MOVE (PERFORM SOMA USING a  USING b) TO r. 
			
			DISPLAY r.
			
			MOVE (PERFORM SUB USING a  USING b) TO r. 
			
			DISPLAY r.
			
			MOVE (PERFORM MULT USING a  USING b) TO r. 
			
			DISPLAY r.
			
			# o assembly da erro de operando quando chama a instrução div ou idiv
			# MOVE (PERFORM DIV USING a  USING b) TO r. 
			
			# DISPLAY r.
			
			ENDCOM.
				
		ENDPROC.	
		
	EXIT.
